version: '3.9'

services:
  postgres_db:
    image: postgres
    container_name: billboard_db
    restart: always
    environment:
      - POSTGRES_NAME=billboard
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - billboard-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '5050:80'
    networks:
      - billboard-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

networks:
  billboard-network:
volumes:
  pgdata:
  pgadmin-data:
